In [2]:
import numpy as np
import pandas as pd

creating data frames

In [20]:
data ={
    'NAME': ['john', 'anna', 'peter', 'linda'],
    'AGE': [28, 34, 29, 42],
    'CITY': ['new york', 'paris', 'berlin', 'london'],
    'SALARY': [65000, 70000, 62000, 85000]
}
pd.DataFrame(data)

    NAME  AGE      CITY  SALARY
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [21]:
data_list = [
    ['john', 28, 'new york', 65000],
    ['anna', 34, 'paris', 70000],
    ['peter', 29, 'berlin', 62000],
    ["linda", 42, 'london', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["name", "age", "city", "salary"]
df2 = pd.DataFrame(data_list, columns = columns)

In [22]:
df2

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

Selection and indexing of column

In [23]:
df2

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [24]:
df2["name"]

0     john
1     anna
2    peter
3    linda
Name: name, dtype: str

In [25]:
df2[["name", "city"]]

    name      city
0   john  new york
1   anna     paris
2  peter    berlin
3  linda    london

creating new coloumn

In [26]:
df2["designation"] = ["doctor", "eng.", "doctor", "eng."]

In [27]:
df2

    name  age      city  salary designation
0   john   28  new york   65000      doctor
1   anna   34     paris   70000        eng.
2  peter   29    berlin   62000      doctor
3  linda   42    london   85000        eng.

In [30]:
df2.drop("designation", axis = 1, inplace = True)

In [31]:
df2

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [32]:
df2

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [33]:
df2.loc[0]

name          john
age             28
city      new york
salary       65000
Name: 0, dtype: object

In [35]:
df2.loc[[0,1]]

   name  age      city  salary
0  john   28  new york   65000
1  anna   34     paris   70000

Selecting subset of rows and columns

In [40]:
df2.loc[[0,1]][["city", "salary"]]

       city  salary
0  new york   65000
1     paris   70000

In [42]:
df2.loc[[2,3]][["name", "age"]]

    name  age
2  peter   29
3  linda   42

conditional statement

In [43]:
df2[df2["age"] > 30]

    name  age    city  salary
1   anna   34   paris   70000
3  linda   42  london   85000

In [45]:
df2[(df2["age"]> 30) & (df2["city"] == "paris")]

   name  age   city  salary
1  anna   34  paris   70000